In [0]:
import numpy as np  # numeric python 수치 파이썬

In [8]:
#ctrl + space, 노트북 : shift+tab, tab
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
b= a.reshape((2,5))#모양 변경
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
b=a.reshape((3,5))
b

ValueError: ignored

In [15]:
b = a.reshape((2,-1)) # -1 : 자동으로 계산
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
b = a.reshape((5,-1))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
#타입 변경 
a.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [18]:
a.astype(np.float32) # 머신러닝에서는 float 자주 사용

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [19]:
#인덱싱 : 배열에서 인덱스를 통해 데이터를 추출
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
b[0,0]

0

In [21]:
b, b[0,0]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), 0)

In [22]:
b, b[0,1]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), 1)

In [23]:
b, b[0,1],b[4,1]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), 1, 9)

In [24]:
b, b[0,1], b[4,1], b[1]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), 1, 9, array([2, 3]))

In [25]:
b, b[0,1], b[4,1], b[1], b[:,0]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), 1, 9, array([2, 3]), array([0, 2, 4, 6, 8]))

In [0]:
#슬라이싱 : 배열의 일부를 자르기

In [31]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a, a[0:3]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2]))

In [33]:
a, a[0:3], a[7:10]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2]), array([7, 8, 9]))

In [34]:
a, a[0:3], a[7:10], a[:3] # : 왼쪽을 생략하면 0

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2]),
 array([7, 8, 9]),
 array([0, 1, 2]))

In [35]:
a, a[0:3], a[7:10], a[:3], a[7:] # : 오른쪽을 생략하면 끝까지

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2]),
 array([7, 8, 9]),
 array([0, 1, 2]),
 array([7, 8, 9]))

In [36]:
a, a[0:3], a[7:10], a[:3], a[7:], a[:]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2]),
 array([7, 8, 9]),
 array([0, 1, 2]),
 array([7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [37]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
b, b[0:2, :]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([[0, 1],
        [2, 3]]))

In [39]:
b, b[0:2, :], b[:2], b[1:4, 1]
#b에서 3,5,7 을 뽑으려면


array([3, 5, 7])

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a[7:]

array([7, 8, 9])

In [42]:
a, a[-3:] # 뒤에서 3개

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([7, 8, 9]))

In [46]:
a, a[-3:], a[-5:-2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([7, 8, 9]), array([5, 6, 7]))

In [51]:
b, b[4]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([8, 9]))

In [52]:
b, b[-1]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([8, 9]))

In [53]:
b, b[-1], b[:, 1]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([8, 9]), array([1, 3, 5, 7, 9]))

In [54]:
b, b[-1], b[:, -1]

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), array([8, 9]), array([1, 3, 5, 7, 9]))

In [57]:
%whos # 변수 출력

No variables match your requested type.


reduce, axis, broadcasting

reduce : 여러개의 데이터를 하나로 줄이는 연산, sum, max, mean...

In [60]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [61]:
np.sum(a)

45

In [62]:
np.sum(b), np.sum(b, axis=0)

(45, array([20, 25]))

In [64]:
b, np.sum(b), np.sum(b, axis=0) # axis=0 (행 row) 행의 값들을, 행 축으로, 행 끼리...

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]), 45, array([20, 25]))

In [66]:
np.sum(b, axis=1) #열 방향.

array([ 1,  5,  9, 13, 17])

In [67]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a + 100 #브로드 캐스팅

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [70]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [73]:
b + a # 차원도 다르고, 모양도 달라서 브로드캐스팅 불가

ValueError: ignored

In [74]:
c = np.array([10, 20]) # 임의의 값으로 배열 생성
c

array([10, 20])

In [75]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [76]:
b+c # 원래는 안되는데 브로드캐스팅이 된 것

array([[10, 21],
       [12, 23],
       [14, 25],
       [16, 27],
       [18, 29]])

In [77]:
b.shape, c.shape

((5, 2), (2,))